CREATE TABLE pomodoros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  duration_type TEXT NOT NULL,
  sessions INTEGER NOT NULL,
  guide_persona TEXT NOT NULL,
  participants TEXT[] NOT NULL,
  slack_ts TEXT NOT NULL,
  status TEXT NOT NULL,
  current_session INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX pomodoros_user_id_idx ON pomodoros (user_id);
CREATE INDEX pomodoros_status_idx ON pomodoros (status);

-- 자동 업데이트 트리거 설정
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_pomodoros_updated_at
BEFORE UPDATE ON pomodoros
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();